name = "Haptik"
license = "MIT"
licenselink = "https://github.com/DamianFlynn/hugo-haptic-theme/blob/main/LICENSE"
description = "A clean, elegant and powerful Hugo theme"
homepage = "https://github.com/DamianFlynn/hugo-haptic-theme"
tags = ["blog", "responsive", "clean", "elegant", "modern"]
features = ["responsive", "dark mode", "code highlighting", "search", "social links"]
min_version = "0.122.0"

[author]
  name = "Damian Flynn"
  homepage = "https://damianflynn.com"

[original]
  name = "Damian Flynn"
  homepage = "https://github.com/damianflynn/"
  repo = "https://github.com/damianflynn/"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.144.0"
